const ACTION_YOUTUBE_DATA = 'ACTION_YOUTUBE_DATA';
const ACTION_QUERY = 'ACTION_QUERY';
const ACTION_YOUTUBE_STATISTICS = 'ACTION_YOUTUBE_STATISTICS';
const ACTION_DELETE_YOUTUBE_QUERY = 'ACTION_DELETE_YOUTUBE_QUERY';
const ACTION_DELETE_YOUTUBE_STATISTICS = 'ACTION_DELETE_YOUTUBE_STATISTICS';

export {
  ACTION_YOUTUBE_DATA,
  ACTION_QUERY,
  ACTION_YOUTUBE_STATISTICS,
  ACTION_DELETE_YOUTUBE_QUERY,
  ACTION_DELETE_YOUTUBE_STATISTICS,
};
