const ACTION_FAVORITES_INFO = 'ACTION_FAVORITES_QUERY_TITLE';
const ACTION_DELETE_QUERY_IN_LIST = 'ACTION_DELETE_QUERY_IN_LIST';
const ACTION_EDIT_QUERY_IN_LIST = 'ACTION_EDIT_QUERY_IN_LIST';
const ACTION_SET_STATUS_REDIRECT_FROM_FAVORITES = 'ACTION_SET_STATUS_REDIRECT_FROM_FAVORITES';
const ACTION_DELETE_ALL_QUERIES = 'ACTION_DELETE_ALL_QUERIES';

export {
  ACTION_FAVORITES_INFO,
  ACTION_DELETE_QUERY_IN_LIST,
  ACTION_EDIT_QUERY_IN_LIST,
  ACTION_SET_STATUS_REDIRECT_FROM_FAVORITES,
  ACTION_DELETE_ALL_QUERIES,
};
